# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/bkh18/ece350-newfinal/final2.runs/synth_1/Wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/bkh18/ece350-newfinal/final2.cache/wt [current_project]
set_property parent.project_path C:/Users/bkh18/ece350-newfinal/final2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/bkh18/ece350-newfinal/final2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files -quiet C:/Users/bkh18/ece350-newfinal/final2.ip_user_files/mem_init_files/stepper.dcp
set_property used_in_implementation false [get_files C:/Users/bkh18/ece350-newfinal/final2.ip_user_files/mem_init_files/stepper.dcp]
add_files -quiet C:/Users/bkh18/ece350-newfinal/final2.sim/sim_1/impl/timing/xsim/stepper_physopt.dcp
set_property used_in_implementation false [get_files C:/Users/bkh18/ece350-newfinal/final2.sim/sim_1/impl/timing/xsim/stepper_physopt.dcp]
add_files -quiet C:/Users/bkh18/ece350-newfinal/final2.srcs/sim_1/imports/ece350-newfinal/final2.runs/impl_1/stepper_opt.dcp
set_property used_in_implementation false [get_files C:/Users/bkh18/ece350-newfinal/final2.srcs/sim_1/imports/ece350-newfinal/final2.runs/impl_1/stepper_opt.dcp]
add_files -quiet C:/Users/bkh18/ece350-newfinal/final2.sim/sim_1/impl/timing/xsim/stepper_placed.dcp
set_property used_in_implementation false [get_files C:/Users/bkh18/ece350-newfinal/final2.sim/sim_1/impl/timing/xsim/stepper_placed.dcp]
add_files -quiet C:/Users/bkh18/ece350-newfinal/final2.srcs/sim_1/imports/ece350-newfinal/final2.runs/impl_1/stepper_placed.dcp
set_property used_in_implementation false [get_files C:/Users/bkh18/ece350-newfinal/final2.srcs/sim_1/imports/ece350-newfinal/final2.runs/impl_1/stepper_placed.dcp]
add_files -quiet C:/Users/bkh18/ece350-newfinal/final2.ip_user_files/mem_init_files/stepper_routed.dcp
set_property used_in_implementation false [get_files C:/Users/bkh18/ece350-newfinal/final2.ip_user_files/mem_init_files/stepper_routed.dcp]
add_files -quiet C:/Users/bkh18/ece350-newfinal/final2.sim/sim_1/impl/timing/xsim/stepper.dcp
set_property used_in_implementation false [get_files C:/Users/bkh18/ece350-newfinal/final2.sim/sim_1/impl/timing/xsim/stepper.dcp]
add_files -quiet C:/Users/bkh18/ece350-newfinal/final2.srcs/sim_1/imports/ece350-newfinal/final2.runs/impl_1/stepper_physopt.dcp
set_property used_in_implementation false [get_files C:/Users/bkh18/ece350-newfinal/final2.srcs/sim_1/imports/ece350-newfinal/final2.runs/impl_1/stepper_physopt.dcp]
add_files -quiet C:/Users/bkh18/ece350-newfinal/final2.srcs/sim_1/imports/ece350-newfinal/final2.runs/synth_1/stepper.dcp
set_property used_in_implementation false [get_files C:/Users/bkh18/ece350-newfinal/final2.srcs/sim_1/imports/ece350-newfinal/final2.runs/synth_1/stepper.dcp]
add_files -quiet C:/Users/bkh18/ece350-newfinal/final2.ip_user_files/mem_init_files/stepper_placed.dcp
set_property used_in_implementation false [get_files C:/Users/bkh18/ece350-newfinal/final2.ip_user_files/mem_init_files/stepper_placed.dcp]
add_files -quiet C:/Users/bkh18/ece350-newfinal/final2.sim/sim_1/impl/timing/xsim/stepper_opt.dcp
set_property used_in_implementation false [get_files C:/Users/bkh18/ece350-newfinal/final2.sim/sim_1/impl/timing/xsim/stepper_opt.dcp]
add_files -quiet C:/Users/bkh18/ece350-newfinal/final2.ip_user_files/mem_init_files/stepper_physopt.dcp
set_property used_in_implementation false [get_files C:/Users/bkh18/ece350-newfinal/final2.ip_user_files/mem_init_files/stepper_physopt.dcp]
add_files -quiet C:/Users/bkh18/ece350-newfinal/final2.ip_user_files/mem_init_files/stepper_opt.dcp
set_property used_in_implementation false [get_files C:/Users/bkh18/ece350-newfinal/final2.ip_user_files/mem_init_files/stepper_opt.dcp]
read_mem {
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/lookup.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/bex.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/final_test.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/branch_mem_edge.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/memory.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/blt.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/mem_bypass.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/md_bypass.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/mem_edge.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/bne.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/exc.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/alu_bypass.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/mem_fbypass.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/multdiv.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/bex_bypass.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/except_bypass.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/branch_bypass.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/addi_basic.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/nop.mem
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/ece350-newfinal/jr.mem
}
read_verilog -library xil_defaultlib {
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/new/stepper.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/processor.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/counter_32.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/register.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/alu.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/multdiv.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/tff.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/barrel_shifter.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/cla_adder_32.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/regfile.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/shift16.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/shift8.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/not_32.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/mux_16.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/shift4.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/mux_32.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/shift2.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/shift1.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/mult_ctrl.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/counter.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/dffe_ref.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/or_32.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/full_adder.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/mult.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/div.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/decoder.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/cla_adder.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/and_32.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/Downloads/Wrapper_timing.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/mux_2.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/mux_4.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/multdiv/regfile/alu/mux_8.v
  C:/Users/bkh18/ece350-newfinal/final2.srcs/sources_1/imports/processor/ROM.v
  C:/Users/bkh18/ece350-newfinal/RAM.v
}
read_vhdl -library xil_defaultlib C:/Users/bkh18/ece350-newfinal/Ps2Interface.vhd
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/bkh18/ece350-newfinal/master.xdc
set_property used_in_implementation false [get_files C:/Users/bkh18/ece350-newfinal/master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Wrapper_utilization_synth.rpt -pb Wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
